spring.application.name=rede-semente
spring.datasource.url=jdbc:postgresql://localhost:5432/rede_semente
spring.datasource.username=camila.maria
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true